Servers/IdentityServer/IdentityServer/Controllers/ResourcesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viking.Identity.Data;
using Viking.Identity.Models;
using Viking.Identity.Server.Authorization;
using Viking.Identity.Server.WebManagement.Models.UserViewModels;

namespace Viking.Identity.Server.WebManagement.Controllers
{
    public class ResourcesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAuthorizationService _authorization;

        public ResourcesController(ApplicationDbContext context, IAuthorizationService authorization)
        {
            _context = context;
            _authorization = authorization;
        }

        public IActionResult VerifyUniqueName(string Name, long? Id)
        {
            if (Id.HasValue)
            {
                if (_context.Resource.Where(r => r.Id != Id.Value).Any(r => r.Name == Name))
                    return Json($"A resource named {Name} already exists");
            }
            else
            {
                if (_context.Resource.Any(g => g.Name == Name))
                    return Json($"A resource named {Name} already exists");
            }
            return Json(true);
        }

        // GET: Resources
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Resource.Include(r => r.Parent).Include(r => r.ResourceType);
            return View(await applicationDbContext.ToListAsync());
        }
         
        // GET: Resources/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var resource = await _context.Resource
                .FirstOrDefaultAsync(m => m.Id == id);

            if (resource == null)
            {
                return NotFound();
            }

            var actionResult = TryRedirectByResourceType("Details", resource.ResourceTypeId, id, () => View(resource));
            return actionResult;
        }

        [HttpGet]
        // GET: Resources/Create
        public IActionResult Create()
        {
            CreateResourceViewModel viewmodel = new CreateResourceViewModel()
            {
                Name = "",
                Description = "",
                ResourceTypeId = null
            };

            ViewBag.AvailableParents = new SelectList(_context.OrgUnit.Where(ou => ou.Id >= 0), nameof(OrganizationalUnit.Id), nameof(OrganizationalUnit.Name));
            ViewBag.AvailableResourceTypes = new SelectList(_context.ResourceTypes, nameof(ResourceType.Id), nameof(ResourceType.Id));
            return View(viewmodel);
        }

        [HttpGet]
        // GET: Resources/Create
        public IActionResult CreateChild(long ParentId)
        {
            CreateResourceViewModel viewmodel = new CreateResourceViewModel()
            {
                Name = "",
                Description = "",
                ResourceTypeId = null,
                ParentId = ParentId
            };

            ViewBag.AvailableParents = new SelectList(_context.OrgUnit.Where(ou => ou.Id >= 0), nameof(OrganizationalUnit.Id), nameof(OrganizationalUnit.Name), viewmodel.ParentId.Value);
            ViewBag.AvailableResourceTypes = new SelectList(_context.ResourceTypes, nameof(ResourceType.Id), nameof(ResourceType.Id));
            return View(nameof(Create), viewmodel);
        }

        /// <summary>
        /// Derived classes of resources can call this method to preserve state if the users wishes to step back and update
        /// the resource type
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpGet]
        // GET: Resources/Create
        public IActionResult CreatePrevious([Bind("Id,Name,Description,ParentId,ResourceTypeId")] CreateResourceViewModel model)
        { 
            ViewBag.AvailableParents = new SelectList(_context.OrgUnit.Where(ou => ou.Id >= 0), nameof(OrganizationalUnit.Id), nameof(OrganizationalUnit.Name), model.ParentId);
            ViewBag.AvailableResourceTypes = new SelectList(_context.ResourceTypes, nameof(ResourceType.Id), nameof(ResourceType.Id));
            return View(nameof(Create), model);
        }

        // POST: Resources/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ParentId,ResourceTypeId")] CreateResourceViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = TryRedirectByResourceType("CreateContinue", model.ResourceTypeId, model, () => {

                    Resource obj = new Resource() { Name = model.Name, Description = model.Description, ParentID = model.ParentId, ResourceTypeId = model.ResourceTypeId };

                    if (false == _authorization.IsParentOrgUnitAdminAsync(HttpContext.User, obj).Result)
                    {
                        return Unauthorized();
                    }

                    _context.Resource.Add(obj);
                    _context.SaveChanges();
                    return View(obj);
                });

                return result;
            }

            ViewBag.AvailableParents = new SelectList(_context.OrgUnit.Where(ou => ou.Id >= 0), nameof(OrganizationalUnit.Id), nameof(OrganizationalUnit.Name), model.ParentId);
            ViewBag.AvailableResourceTypes = new SelectList(_context.ResourceTypes, nameof(ResourceType.Id), nameof(ResourceType.Id));

            return View(model);
        }

        
        // GET: Resources/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var resource = await _context.Resource.FindAsync(id);
            if (resource == null)
            {
                return NotFound();
            }

            return TryRedirectByResourceType(nameof(Edit), resource.ResourceTypeId, id, () => NotFound());
        }

        /*
        // POST: Resources/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,Description,ParentID,ResourceTypeId")] Resource resource)
        {
            if (id != resource.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (false == await _authorization.IsParentOrgUnitAdminAsync(HttpContext.User, resource))
                {
                    return Unauthorized();
                }

                try
                {
                    _context.Update(resource);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResourceExists(resource.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentID"] = new SelectList(_context.Group, "Id", "Name", resource.ParentID);
            ViewData["ResourceTypeId"] = new SelectList(_context.ResourceTypes, "Id", "Id", resource.ResourceTypeId);
            return View(resource);
        }
        */

        // GET: Resources/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var resource = await _context.Resource
                .Include(r => r.Parent)
                .Include(r => r.ResourceType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (resource == null)
            {
                return NotFound();
            }

            return View(resource);
        }

        // POST: Resources/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var resource = await _context.Resource.FindAsync(id);

            if (false == await _authorization.IsParentOrgUnitAdminAsync(HttpContext.User, resource))
            {
                return Unauthorized();
            }

            _context.Resource.Remove(resource);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ResourceExists(long id)
        {
            return _context.Resource.Any(e => e.Id == id);
        }

        /// <summary>
        /// Returns a redirect action if it exists, returns null if the type is resource, throws not implemented otherwise.
        /// </summary>
        /// <param name="ActionName"></param>
        /// <param name="ResourceTypeId"></param>
        /// <param name="RouteValues"></param>
        /// <param name="IsResourceAction">The action to take if the ResourceTypeId == Resource (belongs in this controller)</param>
        /// <returns></returns>
        private IActionResult TryRedirectByResourceType(string ActionName, string ResourceTypeId, object RouteValues, Func<IActionResult> IsResourceAction = null)
        {
            switch (ResourceTypeId)
            {

Servers/IdentityServer/IdentityServer/Views/OrganizationalUnits/Create.cshtml
@model Viking.Identity.Server.WebManagement.Models.UserViewModels.CreateResourceViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>OrganizationalUnit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <partial name="~/Views/Shared/_CreateResourceBasicsPartialForm.cshtml" for="@Model"/>

            @Html.HiddenFor(x => Model.ResourceTypeId)
             
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Servers/IdentityServer/IdentityServer/Views/OrganizationalUnits/Delete.cshtml
@model Viking.Identity.Models.OrganizationalUnit

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrganizationalUnit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Parent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ResourceType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceType.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Servers/IdentityServer/IdentityServer/Views/OrganizationalUnits/Details.cshtml
@model Viking.Identity.Models.OrganizationalUnit

@{
    ViewData["Title"] = "Details";
    ViewData["ShowEdit"] = true;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Organizational Unit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Parent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ResourceType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResourceType.Id)
        </dd>
    </dl>
    <dl class="dl-traditional">
        <dt>
            @Html.DisplayNameFor(model => model.Children)
        </dt>
        <dd style="margin:1em">
            <partial name="~/Views/Shared/_ResourceDetailsGroupedListPartialView.cshtml" model="@Model.Children"/>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Servers/IdentityServer/IdentityServer/Views/OrganizationalUnits/Edit.cshtml
@model Viking.Identity.Models.OrganizationalUnit

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>OrganizationalUnit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Parent" class="control-label"></label>
                <select asp-for="@Model.ParentID" asp-items="@ViewBag.AvailableParents">
                    <option value="">None</option>
                </select>
                <span asp-validation-for="@Model.ParentID" class="text-danger"></span>
            </div>
            <label asp-for="ResourceTypeId" class="control-label"></label>
            @Html.DisplayFor(x => x.ResourceTypeId)
            <input type="hidden" asp-for="ResourceTypeId" class="form-control-static"/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Servers/IdentityServer/IdentityServer/Views/OrganizationalUnits/Index.cshtml
@using Viking.Identity.Server.Authorization
@model IEnumerable<Viking.Identity.Models.OrganizationalUnit>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Children)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @if (item.Parent != null)
                    {
                        <a asp-action="Details" asp-route-id="@item.ParentID.Value">@Html.DisplayFor(modelItem => item.Parent.Name)</a>
                    }
                </td>
                <td>
                    <ul class="no-bullets">
                        @for (int i = 0; i < item.Children.Count(); i++)
                        {
                            <a asp-action="Details" asp-route-id="@item.Children[i].Id">@Html.DisplayFor(modelItem => item.Children[i].Name)</a>
                        } 
                    </ul>
                </td>
                <td>
                    @if ((await AuthorizationService.AuthorizeAsync(User, item, Operations.GroupAccessManager)).Succeeded)
                    {
                        <a asp-action="CreateChild" asp-controller="Resources" asp-route-ParentId="@item.Id">Create Child</a><text> | </text>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a><text> | </text>
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a><text> | </text>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                    else {
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>