Servers/IdentityServer/IdentityServer/Models/UserViewModels/UserRolesViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Viking.Identity.Models;

namespace Viking.Identity.Server.WebManagement.Models.UserViewModels
{
    /// <summary>
    /// Lists all available roles, and lists the roles of each user
    /// </summary>
    public class ListUserRolesViewModel
    {
        public IList<ApplicationRole> AvailableRoles { get; set; }

        public IList<UserRolesViewModel> UsersRoles { get; set; }
    }

    /// <summary>
    /// Lists the roles a user has
    /// </summary>
    public class UserRolesViewModel
    {
        /// <summary>
        /// Id of the user
        /// </summary>
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Username")]
        public string Username { get; set; }
         
        /// <summary>
        /// Roles the user has
        /// </summary>
        public IList<string> Roles { get; set; } 
    }

    /// <summary>
    /// Includes available roles to the user and which roles the user has
    /// </summary>
    public class EditUserRolesViewModel
    {
        /// <summary>
        /// Id of the user
        /// </summary>
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Username")]
        public string Username { get; set; }

        /// <summary>
        /// Roles the user has
        /// </summary>
        public IList<string> Roles { get; set; }

        /// <summary>
        /// Roles available to the user
        /// </summary>
        public IList<ApplicationRole> AvailableRoles { get; set; }
    }
}

Servers/IdentityServer/IdentityServer/Controllers/UserRolesController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Viking.Identity.Data;
using Viking.Identity.Models;
using Viking.Identity.Models.UserViewModels;

namespace Viking.Identity.Controllers
{

    [Route("[controller]/[action]")]
    [Authorize]
    public class UserRolesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;

        public UserRolesController(ApplicationDbContext context,
            ILogger<AccountController> logger)
        {
            _context = context;
            _logger = logger;
        }
          
        // GET: UserRoles 
        public async Task<IActionResult> Index()
        {
            //var Group = ViewData["Group"] as Group; 

            List<ApplicationRole> AvailableRoles = _context.ApplicationRole.ToList();

            var UserRolesModels = (from user in _context.ApplicationUser 
                                  select new UserRolesViewModel
                                  {
                                      Username = user.UserName,
                                      Roles = _context.UserRoles.Where(ur => ur.UserId == user.Id).Select(ur => ur.RoleId).ToList()
                                  }).ToList();

            var listRoles = new ListUserRolesViewModel() { AvailableRoles = AvailableRoles, UsersRoles = UserRolesModels };

            /*
            List < UserRolesViewModel > UserRolesModels = _context.ApplicationUser.Where(u => u.Groups.Any(g => g.Id == GroupId)).Select(
                user => new UserRolesViewModel
                {
                    Username = user.UserName,
                    Roles = _context.UserRoles.Where(ur => ur.UserId == user.Id).Select(ur => ur.RoleId).ToList(),
                    AvailableRoles = AvailableRoles,
                }).ToList();
            */

            return View(listRoles);
            /*
            return View(await _context.ApplicationUser.Select(
                user => new UserRolesViewModel
                {
                    Username = user.UserName,
                    Roles = _context.UserRoles.Where(ur => ur.UserId == user.Id).Select(ur => ur.RoleId).ToList(),
                    AvailableRoles = AvailableRoles,
                })..ToListAsync());
                */
        }

        // GET: UserRoles/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        /*
        // GET: UserRoles/Create
        public ActionResult Create()
        {
            return View();
        }
        */
        /*
        // POST: UserRoles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        */
        /*
        [HttpPost]
        // GET: UserRoles/Edit/5
        public ActionResult Edit(string id)
        {
            return View();
        }*/

        private static bool IsChecked(Microsoft.Extensions.Primitives.StringValues val)
        {
            return val[0] != "false";
        }

        // POST: UserRoles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Special.Roles.Admin)]
        public ActionResult Edit(UserRolesViewModel id, IFormCollection collection)
        {
            try
            {
                var User = _context.ApplicationUser.FirstOrDefault(u => u.UserName == id.Username);
                List<ApplicationRole> AvailableRoles = _context.ApplicationRole.ToList();
                // TODO: Add update logic here
                var listUserRoles = _context.UserRoles.Where(ur => ur.UserId == User.Id).ToList();
                
                foreach(var userRole in AvailableRoles)
                {
                    var form = collection[userRole.Id];
                    bool check = IsChecked(form);
                    if(check && !listUserRoles.Any(ur => ur.RoleId == userRole.Id))
                    {
                        _context.UserRoles.Add(new IdentityUserRole<string>() { UserId = User.Id, RoleId = userRole.Id });
                    }
                    else if(!check && listUserRoles.Any(ur => ur.RoleId == userRole.Id))
                    {
                        //Safety check, make sure we do not remove the last admin user from the admin role
                        if(userRole.Name == Special.Roles.Admin)
                        {
                            var adminRoleId = _context.Roles.FirstOrDefault(ur => ur.Name == Special.Roles.Admin).Id;
                            bool otherAdminUsers = _context.UserRoles.Where(ur => ur.RoleId == adminRoleId && ur.UserId != User.Id).Any();
                            if(otherAdminUsers== false)
                            {
                                _logger.LogWarning("Cannot remove the last admin user");
                                throw new ArgumentException("Cannot remove the last admin user");
                            }
                        }
                        var urToRemove = listUserRoles.First(ur => ur.RoleId == userRole.Id && ur.UserId == User.Id);
                        _context.UserRoles.Remove(urToRemove);
                    }
                }

                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    Details = e.Message
                };

                return View("~/Views/Shared/Error.cshtml",errorModel); 
            }
        }
        /*
        [HttpPost]
        public JsonResult UpdatePublicPostStatus(string id, bool isPublicPost)
        { 
            var result = _context.UserRoles.FirstOrDefault(user => user.UserId == id);
           
            return Json(null);
        }
        */
        /*
        // GET: UserRoles/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UserRoles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }*/
    }
}

Servers/IdentityServer/IdentityServer/Views/UserRoles/Index.cshtml
@using Viking.Identity.Server.WebManagement.Models.UserViewModels
@model Viking.Identity.Server.WebManagement.Models.UserViewModels.ListUserRolesViewModel

@{
    ViewData["Title"] = "Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Role Assignments</h2>
<p>
    Users can be associated with any number of the roles listed below.  Role membership is used by the web service to determine which functions a user can perform.
    Roles currently apply to all volumes.  However for finer grain control an additional test for group membership may be added in the future.
</p>

<!--
<select asp-for="Group" asp-items="Model.RoleSelectList" class="form-control">
    <option value="">Select Group</option>
</select>
    -->

<table class="table">
    <thead>
        <tr>
            <th>
                Username
            </th>
            @{ 
                foreach (var role in Model.AvailableRoles)
                {
                    <th>
                        @role.Name
                    </th>
                }
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            if (!User.IsInRole(Special.Roles.Admin))
            {
                foreach (var item in Model.UsersRoles)
                {
                    <tr>
                        @{ @Html.Partial("View", new EditUserRolesViewModel() { AvailableRoles = Model.AvailableRoles, Username = item.Username, Roles = item.Roles }); }
                    </tr>
                }
            }
            else
            {
                foreach (var item in Model.UsersRoles)
                {
                    <tr>
                        @{ @Html.Partial("ReadOnlyUserRolesView", new EditUserRolesViewModel() { AvailableRoles = Model.AvailableRoles, Username = item.Username, Roles = item.Roles }); }
                    </tr> 
                }
            }
        }
    </tbody>
</table>

Servers/IdentityServer/IdentityServer/Views/UserRoles/ReadOnlyUserRolesView.cshtml
@model Viking.Identity.Server.WebManagement.Models.UserViewModels.EditUserRolesViewModel
 
@using (Html.BeginForm("Edit", "UserRoles", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div hidden="hidden">
        @Html.EditorForModel()
        @Html.EditorFor(model => model.Username)
    </div>

    <td>
        @Html.DisplayFor(model => model.Username)
    </td>

    @foreach (var role in Model.AvailableRoles)
    {
        <td> 
            @Html.CheckBox(@role.Id, Model.Roles.Contains(role.Id), new { @disabled = "disabled" })
        </td>
    }
} 

Servers/IdentityServer/IdentityServer/Views/UserRoles/View.cshtml
@model Viking.Identity.Server.WebManagement.Models.UserViewModels.EditUserRolesViewModel
 
@using (Html.BeginForm("Edit", "UserRoles", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div hidden="hidden">
        @Html.EditorForModel()
        @Html.EditorFor(model => model.Username) 
    </div>

    <td>
        @Html.DisplayFor(model => model.Username)
    </td>

    @foreach (var role in Model.AvailableRoles)
    {
        <td>
            @Html.CheckBox(@role.Id, Model.Roles.Contains(role.Id), new { onclick = "this.form.submit();" })
        </td>
    }
} 