Servers/IdentityServer/IdentityServer/Controllers/GrantedPermissionsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Viking.Identity.Data;
using Viking.Identity.Models;
using Viking.Identity.Server.Authorization;
using Viking.Identity.Server.WebManagement.Extensions;
using Viking.Identity.Server.WebManagement.Models.UserViewModels;

namespace Viking.Identity.Server.WebManagement.Controllers
{
    [Authorize]
    public class GrantedPermissionsController : Controller
    {
        private readonly ApplicationDbContext _context; 
        private readonly IPermissionsViewModelHelper _permissionsHelper;
        private readonly IAuthorizationService _authorization;

        public GrantedPermissionsController(ApplicationDbContext context, IAuthorizationService authorization, IPermissionsViewModelHelper permissionsHelper)
        {
            _context = context;
            _authorization = authorization;
            _permissionsHelper = permissionsHelper;
        }

        // GET: GrantedUserPermissions
        public async Task<IActionResult> Index(long id)
        {
            var applicationDbContext = await GetPermittedForResource(id);

            if(applicationDbContext == null)
            {
                return NotFound("Resource not found");
            }

            if (false == await CanEditResourcePermissions(id))
            {
                return Unauthorized();
            }

            /*
            var authResult = await _authorization.AuthorizeAsync(HttpContext.User, id, IdentityServer.Authorization.Operations.O);
            if (authResult.Succeeded == false)
            {
                return Unauthorized();
            }
            */

            ResourcePermissionsEditGridViewModel model = new ResourcePermissionsEditGridViewModel
            {
                AvailablePermissions = applicationDbContext.AvailablePermissions.Select(p => p.PermissionId).ToList(),
                UserPermissions = _permissionsHelper.ResourcePermissionsByUser(applicationDbContext),
                GroupPermissions = _permissionsHelper.ResourcePermissionsByGroup(applicationDbContext)
            };

            return View(model);
        }

        // GET: GrantedUserPermissions/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (false == await CanEditResourcePermissions(id.Value))
            {
                return Unauthorized();
            }

            var grantedUserPermission = await _context.GrantedUserPermissions
                .Include(g => g.PermittedUser)
                .Include(g => g.Resource)
                .FirstOrDefaultAsync(m => m.ResourceId == id);
            if (grantedUserPermission == null)
            {
                return NotFound();
            }

            return View(grantedUserPermission);
        }

        // GET: GrantedUserPermissions/Create
        public async Task<IActionResult> Create(long ?ResourceId)
        {
            if (ResourceId == null || ResourceId.HasValue == false)
            {
                return NotFound();
            }

            var resource = await _context.Resource.Include(r => r.UsersWithPermissions).Include(r => r.GroupsWithPermissions).FirstAsync(r => r.Id == ResourceId.Value);
            if (resource == null)
            {
                return NotFound();
            }

            var viewData = new CreateGrantedResourcePermissionViewModel()
            {
                Resource = resource,
                Permissions = _context.Permissions.Where(p => p.ResourceTypeId == resource.ResourceTypeId).Select(p => new NamedItemSelectedViewModel<string>() { Id = p.PermissionId, Name = p.PermissionId, Selected = false }).ToList(),
                Users = _context.Users.Select(u => new NamedItemSelectedViewModel<string>() { Id = u.Id, Name = u.UserName, Selected = false }).ToList(),
                //Groups = _context.Group.Select(g => new ItemSelectedViewModel<long>() { Id = g.Id, Name = g.Name, Selected = false }).ToList()
            };

            return View(viewData);
        }

        // POST: GrantedUserPermissions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind(new string[] { nameof(CreateGrantedResourcePermissionViewModel.Resource),
                                                                     nameof(CreateGrantedResourcePermissionViewModel.Users), 
                                                                     nameof(CreateGrantedResourcePermissionViewModel.Permissions)})] CreateGrantedResourcePermissionViewModel grantedPermissions)
        {
             
            if (ModelState.IsValid)
            {
                var resource = await _context.Resource
                                             .Include(r => r.UsersWithPermissions)
                                             .Include(r => r.GroupsWithPermissions)
                                             .Include(r => r.Parent)
                                             .FirstAsync(r => r.Id == grantedPermissions.Resource.Id);
                if(resource == null)
                {
                    return NotFound();
                }

                if (false == await CanEditResourcePermissions(resource))
                {
                    return Unauthorized();
                }

                resource.AddGrantedUserPermissions(grantedPermissions.Permissions, grantedPermissions.Users);
                //resource.AddGrantedGroupPermissions(grantedPermissions.Permissions, grantedPermissions.Groups);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), grantedPermissions.Resource.Id);
            }

            //ViewData["ResourceId"] = new SelectList(_context.Group, "Id", "Name", grantedUserPermission.ResourceId);
            return View(grantedPermissions.Resource); 
        }

        // GET: GrantedUserPermissions/Edit/5
        public async Task<IActionResult> Edit(long id)
        {
            var applicationDbContext = await GetPermittedForResource(id);

            if (applicationDbContext == null)
            {
                return NotFound("Resource not found");
            }

            ResourcePermissionsEditGridViewModel model = new ResourcePermissionsEditGridViewModel
            {
                AvailablePermissions = applicationDbContext.AvailablePermissions.Select(p => p.PermissionId).ToList(),
                UserPermissions = _permissionsHelper.ResourcePermissionsByUser(applicationDbContext),
                GroupPermissions = _permissionsHelper.ResourcePermissionsByGroup(applicationDbContext)
            };

            return View(model);
        }

        // POST: GrantedUserPermissions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind()] ResourcePermissionsEditGridViewModel grantedPermissions)
        { 
            var resource = await _context.Resource
                .Include(r => r.UsersWithPermissions)
                .Include(r => r.GroupsWithPermissions)
                .Include(r => r.Parent)
                .FirstOrDefaultAsync(r => r.Id == id);

            if(resource == null)
            {
                return NotFound();
            }

            if (false == await CanEditResourcePermissions(resource))
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    resource.UpdateUsersPermissions(grantedPermissions.UserPermissions);
                    resource.UpdateGroupsPermissions(grantedPermissions.GroupPermissions);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GrantedUserPermissionExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ResourcesController.Details), "Groups", new { id = id });
            }
//            ViewData["ResourceId"] = new SelectList(_context.Group, "Id", "Name", grantedUserPermission.ResourceId);
            return View(grantedPermissions);
        }

        /*
        // GET: GrantedUserPermissions/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grantedUserPermission = await _context.GrantedUserPermissions
                .Include(g => g.Resource)
                .FirstOrDefaultAsync(m => m.ResourceId == id);
            if (grantedUserPermission == null)
            {
                return NotFound();
            }

            return View(grantedUserPermission);
        }

        // POST: GrantedUserPermissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var grantedUserPermission = await _context.GrantedUserPermissions.FindAsync(id);
            _context.GrantedUserPermissions.Remove(grantedUserPermission);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        */

Servers/IdentityServer/IdentityServer/Controllers/ResourceTypePermissionsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viking.Identity.Data;
using Viking.Identity.Models;

namespace Viking.Identity.Server.WebManagement.Controllers
{
    [Authorize]
    public class ResourceTypePermissionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ResourceTypePermissionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ResourceTypePermissions
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Permissions.Include(r => r.ResourceType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ResourceTypePermissions/Details/5
        public async Task<IActionResult> Details(string ResourceTypeId, string PermissionId)
        {
            if (ResourceTypeId == null || PermissionId == null)
            {
                return NotFound();
            }

            var resourceTypePermission = await _context.Permissions
                .Include(r => r.ResourceType)
                .FirstOrDefaultAsync(m => m.ResourceTypeId == ResourceTypeId && m.PermissionId == PermissionId);
            if (resourceTypePermission == null)
            {
                return NotFound();
            }

            //return View(resourceTypePermission);
            return RedirectToAction("Details", "ResourceTypes", resourceTypePermission.ResourceType);
            //return View("Details", resourceTypePermission.ResourceType);
        }

        /*
        // GET: ResourceTypePermissions/Create
        public IActionResult Create()
        {
            var selectList = new SelectList(_context.ResourceTypes, "Id", "Id");
            ViewData["ResourceTypeId"] = selectList;
            ViewBag.ResourceTypeId = selectList.First().Value;
            return View();
        }
        */

        public async Task<IActionResult> Create(string ResourceTypeId)
        {
            var rt = await _context.ResourceTypes.FirstOrDefaultAsync(rt => rt.Id == ResourceTypeId);
            //ViewData["ResourceTypeId"] = new SelectList(_context.ResourceTypes.Where(rt => rt.Id == ResourceTypeId), "Id", "Id");
            //ViewBag.ResourceTypeId = ResourceTypeId;
            return View(new ResourceTypePermission() { ResourceTypeId = ResourceTypeId, ResourceType = rt});
        }

        // POST: ResourceTypePermissions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Special.Roles.Admin)]
        public async Task<IActionResult> Create([Bind("ResourceTypeId,PermissionId,Description")] ResourceTypePermission resourceTypePermission)
        {
            if (ModelState.IsValid)
            {
                _context.Add(resourceTypePermission);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["ResourceTypeId"] = new SelectList(_context.ResourceTypes, "Id", "Id", resourceTypePermission.ResourceTypeId);
            //return View("Details", resourceTypePermission.ResourceType);
            return RedirectToAction("Details", "ResourceTypes", resourceTypePermission.ResourceType);
        }

        // GET: ResourceTypePermissions/Edit/5
        public async Task<IActionResult> Edit(string ResourceTypeId, string PermissionId)
        {
            if (ResourceTypeId == null || PermissionId == null)
            {
                return NotFound();
            } 

            var resourceTypePermission = await _context.Permissions
                .FirstOrDefaultAsync(m => m.ResourceTypeId == ResourceTypeId && m.PermissionId == PermissionId);
            if (resourceTypePermission == null)
            {
                return NotFound();
            }

            //ViewData["ResourceTypeId"] = new SelectList(_context.ResourceTypes, "Id", "Id", resourceTypePermission.ResourceTypeId);
            return View(resourceTypePermission);
        }

        // POST: ResourceTypePermissions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Special.Roles.Admin)]
        public async Task<IActionResult> Edit(string id, [Bind("ResourceTypeId,PermissionId,Description")] ResourceTypePermission resourceTypePermission)
        {
            if (id != resourceTypePermission.ResourceTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(resourceTypePermission);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResourceTypePermissionExists(resourceTypePermission.ResourceTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ResourceTypeId"] = new SelectList(_context.ResourceTypes, "Id", "Id", resourceTypePermission.ResourceTypeId);
            return RedirectToAction("Details", "ResourceTypes", resourceTypePermission.ResourceType);
            //return View(resourceTypePermission.ResourceType);
        }

        // GET: ResourceTypePermissions/Delete/5
        public async Task<IActionResult> Delete(string ResourceTypeId, string PermissionId)
        {
            if (ResourceTypeId == null || PermissionId == null)
            {
                return NotFound();
            }

            var resourceTypePermission = await _context.Permissions
                .Include(r => r.ResourceType)
                .FirstOrDefaultAsync(m => m.ResourceTypeId == ResourceTypeId && m.PermissionId == PermissionId);
            if (resourceTypePermission == null)
            {
                return NotFound();
            }

            return View(resourceTypePermission);
        }

        // POST: ResourceTypePermissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Special.Roles.Admin)]
        public async Task<IActionResult> DeleteConfirmed([Bind("ResourceTypeId,PermissionId")] ResourceTypePermission key)
        {
            var resourceTypeId = key.ResourceTypeId;
            var resourceTypePermission = await _context.Permissions.FirstAsync(m => m.PermissionId == key.PermissionId && m.ResourceTypeId == key.ResourceTypeId);
            _context.Permissions.Remove(resourceTypePermission);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("Details", "ResourceTypes", await _context.ResourceTypes.FirstOrDefaultAsync(rt => rt.Id == resourceTypeId));
        }

        private bool ResourceTypePermissionExists(string id)
        {
            return _context.Permissions.Any(e => e.ResourceTypeId == id);
        }
    }
}

Servers/IdentityServer/IdentityServer/Views/Shared/EditResourceTypePermissionsList.cshtml
@model Viking.Identity.Models.ResourceType

@if (this.User.IsInRole(Special.Roles.Admin))
{
    <p>
        @Html.ActionLink("Create New Permission", "Create", "ResourceTypePermissions", new { ResourceTypeId = Model.Id })
        <!--<a asp-action="Create" asp-controller="ResourceTypePermissions" asp-ResourceTypeId="@Model.Id">Create New Permission</a>-->
    </p>
}
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Permissions.ElementAt(0).PermissionId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Permissions.ElementAt(0).ResourceTypeId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Permissions.ElementAt(0).Description)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Permissions)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PermissionId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ResourceType.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @if (this.User.IsInRole(Special.Roles.Admin))
                        {
                            @Html.ActionLink("Edit", "Edit", "ResourceTypePermissions", item)<text> | </text>
                            @Html.ActionLink("Details", "Details", "ResourceTypePermissions", item)<text> | </text>
                            @Html.ActionLink("Delete", "Delete", "ResourceTypePermissions", item)
                        }
                        else
                        {
                            @Html.ActionLink("Details", "Details", "ResourceTypePermissions", item)
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

Servers/IdentityServer/IdentityServer/Views/Shared/GroupSelectedChecklist.cshtml
@model IList<Viking.Identity.Server.WebManagement.Models.UserViewModels.GroupSelectedViewModel>


<table>
    @for (int i = 0; i < Model.Count(); i++)
    {
        <tr>
            <td>
                @Html.HiddenFor(x => Model[i].Id)
                @Html.HiddenFor(x => Model[i].Name)
                @Html.CheckBoxFor(x => Model[i].Selected, Model[i].Id)
                @Html.DisplayFor(x => Model[i].Name)
            </td>
        </tr>
    }
</table>

Servers/IdentityServer/IdentityServer/Views/Shared/OrganizationSelectedChecklist.cshtml
@model IList<IdentityServer.Models.UserViewModels.OrganizationSelectedViewModel>


<table>
    @for (int i = 0; i < Model.Count(); i++)
    {
        <tr>
            <td>
                @Html.HiddenFor(x => Model[i].Id)
                @Html.HiddenFor(x => Model[i].Name)
                @Html.CheckBoxFor(x => Model[i].Selected, Model[i].Name)
                @Html.DisplayFor(x => Model[i].Name)
            </td>
        </tr>
    }
</table>

Servers/IdentityServer/IdentityServer/Views/Shared/RoleSelectedChecklist.cshtml
@model IList<Viking.Identity.Server.WebManagement.Models.UserViewModels.RoleSelectedViewModel>

<table>
    @for (int i = 0; i < Model.Count(); i++)
    {
        <tr>
            <td>
                @Html.HiddenFor(x => Model[i].Id)
                @Html.HiddenFor(x => Model[i].Name)
                @Html.CheckBoxFor(x => Model[i].Selected, Model[i].Name)
                @Html.DisplayFor(x => Model[i].Name)
            </td>
        </tr>
    }
</table>

Servers/IdentityServer/IdentityServer/Views/Shared/UserSelectedList.cshtml
@model IList<Viking.Identity.Server.WebManagement.Models.UserViewModels.UserSelectedViewModel>

<table>
    @for(int i = 0; i < Model.Count; i++)
    {
        <tr>
            <td>
                @Html.HiddenFor(x => Model[i].Id)
                @Html.HiddenFor(x => Model[i].Name)
                @Html.CheckBoxFor(x => Model[i].Selected, Model[i].Id)
                @Html.DisplayFor(x => Model[i].Name)
            </td>
        </tr>            
    }
</table>

Servers/IdentityServer/IdentityServer/Views/Shared/_Checkbox_StringKey.cshtml
@model Viking.Identity.Server.WebManagement.Models.UserViewModels.ItemSelectedViewModel<string>

@Html.HiddenFor(x => Model.Id) 
@Html.CheckBoxFor(x => Model.Selected, Model.Id)

Servers/IdentityServer/IdentityServer/Views/Shared/_GroupCheckbox.cshtml
@model Viking.Identity.Server.WebManagement.Models.UserViewModels.GroupSelectedViewModel

@Html.HiddenFor(x => Model.Id)
@Html.HiddenFor(x => Model.Name)
@Html.CheckBoxFor(x => Model.Selected, Model.Name)
@Html.DisplayFor(x => Model.Name)

Servers/IdentityServer/IdentityServer/Views/Shared/_GroupChecklistPartialView.cshtml
@model IList<Viking.Identity.Server.WebManagement.Models.UserViewModels.GroupSelectedViewModel>

<ul class="no-bullets">
    @for (var i = 0; i < Model.Count(); i++)
    {
        <li>
            <partial name="~/Views/Shared/_GroupCheckbox.cshtml" for="@Model[i]" />
        </li>
        //@Html.Partial("~/Views/Shared/GroupSelectedChecklist.cshtml", Model.GroupList)
    }
</ul>

Servers/IdentityServer/IdentityServer/Views/Shared/_NamedCheckbox_StringKey.cshtml
@model Viking.Identity.Server.WebManagement.Models.UserViewModels.NamedItemSelectedViewModel<string>

@Html.HiddenFor(x => Model.Id)
@Html.HiddenFor(x => Model.Name)
@Html.CheckBoxFor(x => Model.Selected, Model.Id)
@Html.DisplayFor(x => Model.Name)

Servers/IdentityServer/IdentityServer/Views/Shared/_ResourceDetailsGroupedListPartialView.cshtml
@using Viking.Identity.Server.Authorization
@model IList<Viking.Identity.Models.Resource>

<dl class="dl-traditional">
    @foreach (var rtype in Model.GroupBy(m => m.ResourceTypeId).OrderBy(m => m.Key))
    {


        string detailsController = null;
        string detailsDescription = null;
        switch (rtype.Key)
        {

            case nameof(Group):
                detailsController = detailsDescription = "Groups";
                break;
            case nameof(Volume):
                detailsController = detailsDescription = "Volumes";
                break;
            case nameof(OrganizationalUnit):
                detailsController = "OrganizationalUnits";
                detailsDescription = "Organizational Units";
                break;
            case nameof(Resource):
                detailsController = detailsDescription = "Resources";
                break;
            default:
                break;
        }
        <dt><u>@detailsDescription</u></dt>

        <dd class="dl-traditional" >
            <table class="grid-settings">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => Model[0].Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => Model[0].Description)
                        </th>
                        <th>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var rows = rtype.OrderBy(r => r.Name).ToList();
                        @for (int i = 0; i < rows.Count(); i++)
                        {
                            <tr>
                                <td>
                                    @if (detailsController != null)
                                    {
                                        <a asp-action="Details" asp-route-id="@rows[i].Id" asp-controller="@detailsController">@Html.DisplayFor(model => rows[i].Name)</a>
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(model => rows[i].Name)
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(model => rows[i].Description)
                                </td>
                                @if (detailsController != null && (await AuthorizationService.AuthorizeAsync(User, rows[i].Id, Operations.GroupAccessManager)).Succeeded)
                                {
                                <td>
                                    <a asp-action="Edit" asp-controller="GrantedPermissions" asp-route-id="@rows[i].Id">Permissions</a> |
                                    @if (ViewData.ContainsKey("ShowEdit") && (bool)ViewData["ShowEdit"] == true)
                                    {
                                        <a asp-action="Edit" asp-route-id="@rows[i].Id" asp-controller="@detailsController">Edit</a>
                                    }
                                    @if (ViewData.ContainsKey("ShowDelete") && (bool)ViewData["ShowDelete"] == true)
                                    {
                                        <a asp-action="Delete" asp-route-id="@rows[i].Id" asp-controller="@detailsController">Delete</a>
                                    }
                                </td>
                                }
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </dd>

    }
</dl> 

Servers/IdentityServer/IdentityServer/Views/Shared/_ResourceDetailsTablePartialView.cshtml
@model IList<Viking.Identity.Models.Resource>

<table class="table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model[0].Description)
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count(); i++)
        {
            <tr>
                <td>
                    @{
                        string detailsController = null;
                        switch (Model[i].ResourceTypeId)
                        {

                            case nameof(Group):
                                detailsController = "Groups";
                                break;
                            case nameof(Volume):
                                detailsController = "Volumes";
                                break;
                            case nameof(OrganizationalUnit):
                                detailsController = "OrganizationalUnits";
                                break;
                            case nameof(Resource):
                                detailsController = "Resources";
                                break;
                            default:
                                @Html.DisplayFor(model => Model[i].ResourceTypeId)
                                break;
                        }
                        @if (detailsController != null)
                        {
                            <a asp-action="Details" asp-route-id="@Model[i].Id" asp-controller="@detailsController">@Html.DisplayFor(model => Model[i].Name)</a>
                        }
                        else
                        {
                            @Html.DisplayFor(model => Model[i].Name)
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(model => Model[i].Description)
                </td>
            </tr>
        }
    </tbody>
</table>

Servers/IdentityServer/IdentityServer/Views/Shared/_UserChecklistPartialView.cshtml
@model IList<Viking.Identity.Server.WebManagement.Models.UserViewModels.UserSelectedViewModel>

<ul class="no-bullets">
    @for (var i = 0; i < Model.Count(); i++)
    {
        <li>
            <partial name="~/Views/Shared/_UserCheckbox.cshtml" for="@Model[i]" />
        </li>
        //                    @Html.Partial("~/Views/Shared/UserSelectedList.cshtml", Model.UserList)
    }
</ul>

Servers/IdentityServer/IdentityServer/Views/Shared/_UserPermissionTableRow.cshtml
@model Viking.Identity.Server.WebManagement.Models.UserViewModels.UserResourcePermissionsViewModel

@{
    ViewData["Title"] = "Permissions Granted to Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IList<string> AvailablePermissions = ViewData["AvailablePermissions"] as IList<string>;
}

<td>
    <label asp-for="@Model.GranteeId" class="control-label"></label>
</td>

 